# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    # node.js
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: stable

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version && npm --version
  - echo -- BABEL 7 --
  - npm test
  - echo Replacing Babel 7 with Babel 6
  - npm remove
      babel-core
      babel-plugin-external-helpers
      babel-plugin-transform-decorators
      babel-plugin-transform-runtime
      babel-preset-es2015
  - npm install
      babel-core@6
      babel-plugin-external-helpers@6
      babel-plugin-transform-decorators@6
      babel-plugin-transform-runtime@6
      babel-preset-es2015@6
  - echo -- BABEL 6 --
  - npm test

matrix:
  fast_finish: false

# cache:
#   - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json     # npm cache
#   - node_modules -> package.json                                    # local npm modules
